### ISSUE TITLE
No module named 'bioparameters'

### ISSUE THREAD

**Issue by ManuelCarrascoY** [openworm/c302#24]
I installed c302, following the instructions. When running to create a new network. I entered the following command. 

` c302 MyNetwork parameters_C -cells ["AVBR","VD3"] -cellstostimulate ["AVBR"] -paramoverride {"unphysiological_offset_current":"2.9pA"} -duration 300`

**Comment by pgleeson** [comment]
There were some issues with the importing that Python 3 (I assume you're using) didn't like. Should be fixed in this: https://github.com/openworm/c302/commit/8eba1d5c14301be2b55a265b8ee09e9b50879ac0#diff-35125e73fe3332e2b0060c628bb30893. Let me know if you've any other issue.

**Comment by ManuelCarrascoY** [comment]
It solved the issue. However, something else appeared trying to see the structure of the network using pyNeuroML. 

`pynml MyNetwork.net.nml -graph 4c`

The message was:

`File "/opt/anaconda3/lib/python3.7/site-packages/neuromllite-0.1.9-py3.7.egg/neuromllite/GraphVizHandler.py", line 14, in <module>
from graphviz import Digraph
ModuleNotFoundError: No module named 'graphviz'`

**Comment by pgleeson** [comment]
That should be fixed by installing the GraphViz package:

    apt-get install graphviz

(test installation with: dot -V), and then install the python wrapper for it:

      pip install graphviz

**Comment by pgleeson** [comment]
Fixed in master
