### ISSUE TITLE
Can't connect to PyOpenWorm

### ISSUE THREAD

**Issue by ManuelCarrascoY** [openworm/c302#25]
I called the command 

`c302 -h`

And found this error

`FileNotFoundError: [Errno 2] No such file or directory: '/Users/username/PyOpenWorm/.pow/worm.db.lock'
Failed to open the data source because: Could not open the database file "/Users/username/PyOpenWorm/.pow/worm.db"`
`c302      >>>  Can't connect to PyOpenWorm: ...`
`PyOpenWorm connection failed: Could not open the database file "/Users/username/PyOpenWorm/.pow/worm.db". Perhaps you need to do a "pow clone"?`

It seems like c302 cannot connect to PyOpenWorm. Where can I access this database?

**Comment by mwatts15** [comment]
Thanks, @ManuelCarrascoY . c302 gets its PyOpenWorm database from the https://github.com/openworm/OpenWormData repo. There are some other issues with how PyOpenWorm is used in c302 that I'm addressing. Will update this issue when they are resolved.

**Comment by pgleeson** [comment]
@ManuelCarrascoY c302 uses a specific earlier (pre renaming to owmeta) version of PyOpenWorm, which can be installed by looking at the Travis CI install script here: https://github.com/openworm/c302/blob/master/.travis.yml#L41.

Note however, none of the functionality of c302 is currently dependent on PyOpenWorm, it just really adds metadata to the generated files, e.g. types of neuron, neurotransmitter etc. https://github.com/openworm/c302/blob/master/examples/c302_C0_Oscillator.net.nml#L140. The errors you are getting can be ignored if you have any issue installing POW. 

In the longer term there is a plan to pull connectivity data directly from PyOpenWorm/owmeta, as opposed to at present where data is taken from the included spreadsheets (using helper classes, e.g. see https://github.com/openworm/c302/blob/master/c302/UpdatedSpreadsheetDataReader2.py). This shouldn't prevent the use/development of the core features of c302 though in its current form.

**Comment by mwatts15** [comment]
Created PR #26. It suppresses a couple of the logging messages after they are first emitted. The interface to owmeta will be different in that you'll retrieve the data from a bundle which has logic to download the bundle if needed and won't need to specify a specific project directory since bundles download, by default, to a location in the user's home directory.

**Comment by pgleeson** [comment]
@ManuelCarrascoY Let me know if you managed to get it installed and close this issue if it's working for you.

**Comment by ManuelCarrascoY** [comment]
Hello, yes it is working. Thanks for the help.
