### ISSUE TITLE
Move tests to travis-ci.com

### ISSUE THREAD

**Issue by pgleeson** [openworm/c302#38]
Need to move tests on this from travis-ci.org to travis-ci.com. They will eventually move to github actions, but as a short term solution (since travis-ci.org will shut on June 15th) tests can be moved to travis-ci.com.

This seems to be set up in Settings, but there is a block on this under Third Party Access
<img width="1163" alt="Screenshot 2021-06-07 at 12 43 25" src="https://user-images.githubusercontent.com/1556687/121011808-f08d2f00-c78e-11eb-8b99-082f32ac12d2.png">
@mwatts15 It has you down as requesting this. Any reason not to grant access to this?

**Comment by mwatts15** [comment]
@pgleeson I don't remember making that request. I guess they request private data access just because they *can* access private repos. I don't see a reason to not grant it.

**Comment by pgleeson** [comment]
Ok, @mwatts15. I've taken that restriction away and now the migration to travis-ci.com works fine, see https://travis-ci.com/github/openworm (some failing there, but I needed to update them anyway...).

If you do want to migrate to travis-ci.com, the simplest way as far as I can see is:
1) Go to the existing page for your tests on org, e.g. https://travis-ci.org/github/openworm/owmeta
2) Replace org by com in the url and load
3) Click on the Migrate button on the new page
4) After a short wait, make a change on your repo, e.g. moving org->com for the travis link on the README.

and it should kick off test on com from now on.

**Comment by mwatts15** [comment]
Thanks! I'm going to move to GH actions, I've just been slow-walking it,
but it's pretty straightforward.
